# Generated by Django 5.0.7 on 2025-10-26 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("año", models.IntegerField()),
                (
                    "monto_asignado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
            ],
            options={
                "unique_together": {("comunidad", "año")},
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Borrador", "Borrador"),
                            ("Enviado a Revision", "Enviado a Revisión"),
                            ("Aprobado", "Aprobado"),
                            ("Rechazado", "Rechazado"),
                            ("En Ejecución", "En Ejecución"),
                            ("Finalizado", "Finalizado"),
                        ],
                        default="Borrador",
                        max_length=50,
                    ),
                ),
                (
                    "presupuesto_asignado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("descripcion", models.TextField()),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("comentarios_aprobacion", models.TextField(blank=True)),
                (
                    "documento_asamblea",
                    models.FileField(
                        blank=True, null=True, upload_to="proyectos/asambleas/"
                    ),
                ),
                (
                    "documento_cotizaciones",
                    models.FileField(
                        blank=True, null=True, upload_to="proyectos/cotizaciones/"
                    ),
                ),
                (
                    "documento_elegido",
                    models.FileField(
                        blank=True, null=True, upload_to="proyectos/elegidos/"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proyectos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectos.periodo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                ("fecha_socio", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
            ],
        ),
    ]
