# Generated by Django 5.0.7 on 2025-10-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        ("periodos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "presupuesto_total",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("estado", models.CharField(max_length=50)),
                (
                    "total_rendido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estado_rendicion", models.CharField(max_length=50)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="periodos.periodo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asamblea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("acta", models.FileField(upload_to="asambleas/")),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
                (
                    "proyectos_propuestos",
                    models.ManyToManyField(to="proyectos.proyecto"),
                ),
            ],
        ),
    ]
