# Generated by Django 5.0.7 on 2025-10-14 16:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidades", "0001_initial"),
        ("proyectos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="actualizado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_aprobados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="comentarios_aprobacion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="creado_en",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proyecto",
            name="documento_asamblea",
            field=models.FileField(
                blank=True, null=True, upload_to="proyectos/asambleas/"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="documento_cotizaciones",
            field=models.FileField(
                blank=True, null=True, upload_to="proyectos/cotizaciones/"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="documento_elegido",
            field=models.FileField(
                blank=True, null=True, upload_to="proyectos/elegidos/"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fecha_aprobacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Borrador", "Borrador"),
                    ("Enviado a Revision", "Enviado a Revisión"),
                    ("Aprobado", "Aprobado"),
                    ("Rechazado", "Rechazado"),
                    ("En Ejecución", "En Ejecución"),
                    ("Finalizado", "Finalizado"),
                ],
                default="Borrador",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("año", models.IntegerField()),
                (
                    "monto_asignado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
            ],
            options={
                "unique_together": {("comunidad", "año")},
            },
        ),
        migrations.AddField(
            model_name="proyecto",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proyectos.periodo",
            ),
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("rut", models.CharField(max_length=20, unique=True)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
                ("fecha_socio", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
            ],
        ),
    ]
