# Generated by Django 5.0.7 on 2025-11-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0002_remove_documento_asamblea"),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="fecha_fin",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="fecha_inicio",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="presupuesto_total",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="acta",
            field=models.FileField(blank=True, null=True, upload_to="proyectos/actas/"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="cotizaciones",
            field=models.FileField(
                blank=True, null=True, upload_to="proyectos/cotizaciones/"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="elegido",
            field=models.FileField(
                blank=True, null=True, upload_to="proyectos/elegido/"
            ),
        ),
        migrations.DeleteModel(
            name="Asamblea",
        ),
    ]
