# Generated by Django 5.0.7 on 2025-11-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proyectos",
            "0002_remove_proyecto_descripcion_remove_proyecto_estado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="descripcion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(default="Borrador", max_length=50),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="presupuesto_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="estado_rendicion",
            field=models.CharField(default="Pendiente", max_length=50),
        ),
    ]
