# Generated by Django 5.0.7 on 2025-11-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0003_proyecto_descripcion_proyecto_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(default="Pendiente", max_length=50),
        ),
    ]
