# Generated by Django 5.0.7 on 2025-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidad",
                    models.CharField(
                        choices=[
                            ("Proyecto", "Proyecto"),
                            ("Gasto", "Gasto"),
                            ("Beneficiario", "Beneficiario"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entidad_id", models.IntegerField()),
                ("tipo", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="documentos/")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
