# Generated by Django 5.0.7 on 2025-10-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidades", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunidad",
            name="monto_asignado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
