# Generated by Django 5.0.7 on 2025-10-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comunidades", "0003_comunidad_monto_asignado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comunidad",
            name="monto_asignado",
        ),
    ]
