# Generated by Django 5.0.7 on 2025-08-31 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En Ejecución", "En Ejecución"),
                            ("Finalizado", "Finalizado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "presupuesto_asignado",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("descripcion", models.TextField()),
                ("categoria", models.CharField(max_length=255)),
                (
                    "monto_invertido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
            ],
        ),
    ]
