# Generated by Django 5.0.7 on 2025-09-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Proyecto",
        ),
    ]
