# Generated by Django 5.0.7 on 2025-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="default_user", max_length=150, unique=True),
        ),
    ]
