# Generated by Django 5.0.7 on 2025-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("rut", models.CharField(max_length=12)),
                ("tipo", models.CharField(default="general", max_length=50)),
            ],
        ),
    ]
