# Generated by Django 5.0.7 on 2025-10-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auditores", "0001_initial"),
        ("comunidades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditor",
            name="comunidades",
            field=models.ManyToManyField(to="comunidades.comunidad"),
        ),
    ]
