# Generated by Django 5.0.7 on 2025-10-26 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Ejecución", "Ejecución"),
                            ("Rendición", "Rendición"),
                            ("Estado de Cuenta", "Estado de Cuenta"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha", models.DateField()),
                ("pdf_url", models.URLField()),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectos.proyecto",
                    ),
                ),
            ],
        ),
    ]
