# Generated by Django 5.0.7 on 2025-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                ("categoria", models.CharField(max_length=100)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Aprobado", "Aprobado"),
                            ("Rechazado", "Rechazado"),
                        ],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoBancario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metodo", models.CharField(max_length=50)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                ("referencia", models.CharField(max_length=255)),
                ("conciliado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TipoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Ingreso", "Ingreso"), ("Egreso", "Egreso")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
