# Generated by Django 5.0.7 on 2025-09-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        ("finanzas", "0001_initial"),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proyectos.proyecto"
            ),
        ),
        migrations.AddField(
            model_name="movimientobancario",
            name="comunidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="comunidades.comunidad"
            ),
        ),
    ]
