# Generated by Django 5.0.7 on 2025-09-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0002_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientobancario",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuarios.customuser",
            ),
        ),
        migrations.AddField(
            model_name="movimientobancario",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finanzas.tipomovimiento",
            ),
        ),
    ]
