# Generated by Django 5.0.7 on 2025-10-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0001_initial"),
        ("periodos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimiento",
            name="periodo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="periodos.periodo"
            ),
        ),
    ]
