# Generated by Django 5.0.7 on 2025-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("periodos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodo",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
