# Generated by Django 5.0.7 on 2025-10-26 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunidades", "0003_comunidad_monto_asignado"),
        ("periodos", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodo",
            name="usuario",
        ),
        migrations.AddField(
            model_name="periodo",
            name="comunidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periodos",
                to="comunidades.comunidad",
            ),
        ),
        migrations.AddField(
            model_name="periodo",
            name="monto_asignado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
