# Generated by Django 5.0.7 on 2025-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("periodos", "0003_remove_periodo_usuario_periodo_comunidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodo",
            name="monto_anterior",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
