# Generated by Django 5.0.7 on 2025-10-28 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rendicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("numero_documento", models.CharField(max_length=100)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("Factura", "Factura"),
                            ("Boleta", "Boleta"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("monto_rendido", models.DecimalField(decimal_places=2, max_digits=12)),
                ("numero_comprobante_pago", models.CharField(max_length=100)),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("Transferencia", "Transferencia"),
                            ("Efectivo", "Efectivo"),
                            ("Cheque", "Cheque"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_pago", models.DateField()),
                ("rut_proveedor", models.CharField(max_length=20)),
                ("rut_beneficiario", models.CharField(max_length=20)),
                (
                    "estado_aprobacion",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Aprobado", "Aprobado"),
                            ("Rechazado", "Rechazado"),
                        ],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
                ("fecha_rendicion", models.DateField()),
                (
                    "documentos_adjuntos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rendiciones_adjuntas",
                        to="documentos.documento",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectos.proyecto",
                    ),
                ),
            ],
        ),
    ]
