# Generated by Django 5.0.7 on 2025-10-26 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rendicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_rendido", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descripcion", models.TextField()),
                (
                    "estado_aprobacion",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("Aprobado", "Aprobado"),
                            ("Rechazado", "Rechazado"),
                        ],
                        default="Pendiente",
                        max_length=50,
                    ),
                ),
                ("fecha_rendicion", models.DateField()),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documentos.documento",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectos.proyecto",
                    ),
                ),
            ],
        ),
    ]
