# Generated by Django 5.0.7 on 2025-11-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rendiciones", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rendicion",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="fecha_pago",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="monto_pagado",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="numero_comprobante_pago",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="numero_documento",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="rut_beneficiario",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="rut_proveedor",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="tipo_documento",
        ),
        migrations.RemoveField(
            model_name="rendicion",
            name="tipo_pago",
        ),
        migrations.AlterField(
            model_name="rendicion",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
