# Generated by Django 5.0.7 on 2025-11-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "rendiciones",
            "0002_remove_rendicion_fecha_remove_rendicion_fecha_pago_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rendicion",
            name="estado_aprobacion",
        ),
    ]
