# Generated by Django 5.0.7 on 2025-09-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("rut", models.CharField(max_length=12)),
                ("monto_beca", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
            ],
        ),
    ]
