# Generated by Django 5.0.7 on 2025-10-26 02:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("Admin Consejo", "Admin Consejo"),
                            ("Admin Comunidad", "Admin Comunidad"),
                            ("Auditor", "Auditor"),
                            ("Visor", "Visor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
