# Generated by Django 5.0.7 on 2025-10-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("nombre", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="documentos/")),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
    ]
