# Generated by Django 5.0.7 on 2025-10-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="asamblea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proyectos.asamblea",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proyectos.proyecto",
            ),
        ),
    ]
