# Generated by Django 5.0.7 on 2025-09-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="subido_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.customuser"
            ),
        ),
    ]
