# Generated by Django 5.0.7 on 2025-11-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="asamblea",
        ),
    ]
